\begin{lstlisting}[caption = {\texttt{Makefile}}]
obj-m := naive_fs.o
KDIR := /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

all:
	make -C $(KDIR) M=$(PWD) modules

clean:
	make -C $(KDIR) M=$(PWD) clean
\end{lstlisting}
